### This is my RScript to calculate TPM mean, minimum, median, and maximum values from the 'abundance.tsv' tables generated by kallisto  
## Setting my directory to where my kallisto output files are kept
setwd("/home/basante1/PipelineProject_Bright_Asante/results")


### Now I will calculate the mean, median, max, and minimum tpm values for each of my transcript results from the 'abundance.tsv' tables generated
## Calculating values for SRX2896360 (Donor 1(2dpi))
data <- read.table("./SRX2896360/abundance.tsv", header = TRUE)
data_tpm_values <- data$tpm
min_tpm1 <- min(data$tpm)
med_tpm1 <- median(data$tpm)
mean_tpm1 <- mean(data$tpm)
max_tpm1 <- max(data$tpm)

## Calculating values for SRX2896363 (Donor 1(6dpi))
data <- read.table("./SRX2896363/abundance.tsv", header = TRUE)
data_tpm_values <- data$tpm
min_tpm2 <- min(data$tpm)
med_tpm2 <- median(data$tpm)
mean_tpm2 <- mean(data$tpm)
max_tpm2 <- max(data$tpm)


## Calculating values for SRX2896374 (Donor 2(3dpi))
data <- read.table("./SRX2896374/abundance.tsv", header = TRUE)
data_tpm_values <- data$tpm
min_tpm3 <- min(data$tpm)
med_tpm3 <- median(data$tpm)
mean_tpm3 <- mean(data$tpm)
max_tpm3 <- max(data$tpm)


## Calculating values for SRX2896375 (Donor 2(6dpi))
data <- read.table("./SRX2896375/abundance.tsv", header = TRUE)
data_tpm_values <- data$tpm
min_tpm4 <- min(data$tpm)
med_tpm4 <- median(data$tpm)
mean_tpm4 <- mean(data$tpm)
max_tpm4 <- max(data$tpm)

### I have finished calculating values for all my transcripts. I have to keep the results in a data frame and write it to my logfile.
### Here, I am tracking back to add all my result values to a data frame in the format below
table <- data.frame(sample = c('SRX2896360', 'SRX2896363', 'SRX2896374', 'SRX2896375'), 
                    condition = c('Donor1(2dpi)', 'Donor1(6dpi)', 'Donor3(2dpi)', 'Donor3(6dpi)'), 
                    min_tpm = c(min_tpm1, min_tpm2, min_tpm3, min_tpm4), 
                    med_tpm = c(med_tpm1, med_tpm2, med_tpm3, med_tpm4), 
                    mean_tpm = c(mean_tpm1, mean_tpm2, mean_tpm3, mean_tpm4),
                    max_tpm = c(max_tpm1, max_tpm2, max_tpm3, max_tpm4))

output_file <- file("./../PipelineProject.log", 'a')
tpmstats <-write.table(table, file = output_file, sep = "\t", row.names = FALSE)
write(tpmstats, output_file, sep = " ") ## I wanted to line separate my data frame from my original content in my logfile, but I could not find a better way to do it. It just adds it directly and does not separate it like how I wanted to

